[default]
current_env='work'

[personal]
AUTOLOAD_SSH_KEYS=['~/.ssh/git_personal']
SHELL_CONFIGS=[]

[work]
AUTOLOAD_SSH_KEYS=['~/.ssh/git_personal', '~/.ssh/bitbucket_work']
SHELL_CONFIGS=['$dotfiles_path/work/.lume_shellrc']
