-- return {
--   "nvim-neo-tree/neo-tree.nvim",
--   dependencies = {
--     "nvim-lua/plenary.nvim",
--     "nvim-tree/nvim-web-devicons",
--     "MunifTanjim/nui.nvim",
--     "3rd/image.nvim" -- Optional image support in preview window
--   },
--   config = function()
--     require("neo-tree").setup {
--       close_if_last_window = true,
--       filesystem = {
--         hijack_netrw_behavior = "open_default",
--         follow_current_file = { enabled = false },
--         filtered_items = {
--           visible = true,
--           show_hidden_count = true,
--           hide_dotfiles = false,
--           hide_gitignore = false
--         }
--       }
--     }
--
--     vim.keymap.set("n", "<leader>ft", "<cmd>Neotree toggle position=float<CR>", { desc = "Toggle file explorer" })
--   end
-- }
